// Kept for reproducibility (2026-08-30): the Sol-written Georgia Team Capsule. Data pack + sources live in .superpowers/uga-annual (not committed); renderer in the session scratchpad.
// Georgia 2026 Preseason Annual — written by Sol, section by section, from a
// verified fact pack; Terra tightens; the fact checker grades each section.
import { readFileSync, writeFileSync, readdirSync, existsSync } from "node:fs";
for (const l of readFileSync(".env.local", "utf8").split("\n")) { const i = l.indexOf("="); if (i > 0 && !l.startsWith("#")) process.env[l.slice(0, i).trim()] ??= l.slice(i + 1).trim(); }
const { callJSON, modelForRole } = await import("../lib/editorial-v3/models.ts");
const { S, N, arr, obj, v3Prompt, dateLine } = await import("../lib/editorial-v3/v3-context.ts");
const { factCheckSources } = await import("../lib/editorial-v3/fact-check.ts");
const D = ".superpowers/uga-annual";
const data = JSON.parse(readFileSync(`${D}/data.json`, "utf8"));
const ONLY = process.argv.slice(2);

// ------------------------------------------------------------ the fact pack
const g25 = (data.games2025 as any[]).map((g) => { const home = g.homeTeam === "Georgia"; const us = home ? g.homePoints : g.awayPoints, them = home ? g.awayPoints : g.homePoints; return { date: g.startDate.slice(0, 10), opp: home ? g.awayTeam : g.homeTeam, home, us, them, w: us > them, notes: g.notes ?? "" }; });
const pf = g25.reduce((a, g) => a + g.us, 0), pa = g25.reduce((a, g) => a + g.them, 0);
const stat = (k: string) => (data.stats2025 as any[]).find((s) => s.statName === k)?.statValue;
const draft = (data.draft2026 as any[]).filter((p) => /georgia$/i.test(p.collegeTeam ?? "")).map((p) => `Round ${p.round}, pick ${p.overall}: ${p.name}, ${p.position}`);
const portalIn = (data.portal as any[]).filter((p) => p.destination === "Georgia").map((p) => `${p.firstName} ${p.lastName} (${p.position}, from ${p.origin}${p.stars ? `, ${p.stars}-star` : ""})`);
const portalOut = (data.portal as any[]).filter((p) => p.origin === "Georgia").map((p) => `${p.firstName} ${p.lastName} (${p.position}, to ${p.destination ?? "undecided"})`);
const ret = data.returning[0];
const FACTS = `VERIFIED TEAM FACTS — GEORGIA, as of ${new Date().toDateString()} (CFBD feed + the site's fact sheet). Never contradict these; never go beyond them without a source below.

${data.factSheet}

2025 RESULTS (${g25.filter((g) => g.w).length}-${g25.filter((g) => !g.w).length}; points for ${pf} / against ${pa} in 14 games = ${(pf / 14).toFixed(1)} scored, ${(pa / 14).toFixed(1)} allowed per game):
${g25.map((g) => `  ${g.date} ${g.home ? "vs" : "at"} ${g.opp} ${g.us}-${g.them} ${g.w ? "W" : "L"}${g.notes ? " — " + g.notes : ""}`).join("\n")}

2025 TEAM STATS (14 games): total yards ${stat("totalYards")} (allowed ${stat("totalYardsOpponent")}); net passing ${stat("netPassingYards")} (allowed ${stat("netPassingYardsOpponent")}); rushing ${stat("rushingYards")} on ${stat("rushingAttempts")} carries (allowed ${stat("rushingYardsOpponent")}); passing TD ${stat("passingTDs")}, rushing TD ${stat("rushingTDs")}; sacks ${stat("sacks")} (allowed ${stat("sacksOpponent")}); TFL ${stat("tacklesForLoss")}; interceptions ${stat("interceptions")}, thrown ${stat("passesIntercepted")}; turnovers ${stat("turnovers")} (forced ${stat("turnoversOpponent")}); third downs ${stat("thirdDownConversions")}/${stat("thirdDowns")} (opponents ${stat("thirdDownConversionsOpponent")}/${stat("thirdDownsOpponent")}); fourth downs ${stat("fourthDownConversions")}/${stat("fourthDowns")}; first downs ${stat("firstDowns")}; penalties ${stat("penalties")} for ${stat("penaltyYards")} yards; time of possession ${Math.round(Number(stat("possessionTime")) / 14 / 60)} min/game.

2025 PLAYER STATS (CFBD):
${readFileSync(`${D}/players2025.txt`, "utf8")}

2026 NFL DRAFT — GEORGIA PLAYERS TAKEN (${draft.length}):
${draft.map((d) => "  " + d).join("\n")}

TRANSFER PORTAL 2026 — IN (${portalIn.length}): ${portalIn.join("; ")}
TRANSFER PORTAL 2026 — OUT (${portalOut.length}): ${portalOut.join("; ")}

RETURNING PRODUCTION (CFBD PPA share, 2026): overall ${(ret.percentPPA * 100).toFixed(1)}% · passing ${(ret.percentPassingPPA * 100).toFixed(1)}% · receiving ${(ret.percentReceivingPPA * 100).toFixed(1)}% · rushing ${(ret.percentRushingPPA * 100).toFixed(1)}%. 2026 recruiting class rank: No. ${data.recruiting[0]?.rank} (247 composite points ${data.recruiting[0]?.points}). Team talent composite 2026: ${data.talent[0]?.talent}.

${data.roster}

JOSH PATE — ON THE RECORD (the site's live positions; the column is under his byline and must not contradict them):
- The JP Poll (Josh's personal board): Georgia No. 1. JP Rating: a tenth of a point ahead of No. 2 Ohio State's 94.9 — i.e. about 95.0 (state it as "the top rating on the board", do not invent decimals beyond that).
- The Pate State Model (the site's power ratings): Ohio State No. 1, Georgia No. 2. The Model crowns Ohio State the most likely champion.
- Josh's published 12-team bracket (Aug. 19): Georgia the No. 1 seed with a first-round bye; champion GEORGIA, final "Georgia 31, Ohio State 28"; Ohio State No. 2 seed, Clemson No. 3, Boise State No. 4, Texas No. 5, Oregon No. 6, Penn State No. 7, LSU No. 8, Notre Dame No. 9, Alabama No. 10, Miami No. 11, Indiana No. 12.
- An earlier document (CFP Prediction v1.0, Aug. 5) named Notre Dame champion. The bracket is the later position and the site's live one; treat Georgia-as-champion as Josh's current call, and never mention the earlier document in the prose.
- Josh's Ohio State annual (Aug. 18) called Ohio State's roster "the highest ceiling in America" and projected Ohio State 11–1. The two annuals must not contradict each other on Georgia–Ohio State facts.
- CONSISTENCY LEDGER: every game pick you make here becomes a logged claim; Georgia must be the SEC champion and national champion in this annual (that is the bracket). Regular-season losses are allowed if you argue them; the SEC title game and the playoff are wins.`;
const SOURCES = readdirSync(`${D}/sources`).map((f) => readFileSync(`${D}/sources/${f}`, "utf8")).join("\n\n=====\n\n");
const EXEMPLAR = readFileSync("docs/content/ohio-state-2026-preseason-annual.md", "utf8").replace(/<!--[\s\S]*?-->/, "").slice(0, 32000);

const VOICE = v3Prompt("josh-column-additive").split("HOW A COLUMN IS BUILT")[0];
const SYSTEM = `You are writing the Georgia section of The Pate State Preseason Annual — the "Team Capsule" — under Josh Pate's byline, exactly in the shape of the Ohio State capsule reproduced below (its structure, its devices, its density). This is the annual's gold standard; match its register, never copy its sentences. Ohio State's facts are Ohio State's; every Georgia fact comes from the FACT PACK and the SOURCES, nothing else.

${VOICE}

THE ANNUAL'S LAWS: numbers everywhere a vague quantifier could live (returning starts, sacks allowed, draft picks lost, rating points). Name the program's riskiest personnel decision plainly as the boldest bet, and say what has to be true for it to work, with a watch date. Market framing, never dunk framing ("the market is too high on", never "overrated"). Every prediction is falsifiable and dated; every game gets a pick. "Fair witness" means the flaw gets named next to the strength. House devices you may use: Fair-Witness Flaw, ⏱ Watch, Grade, The Ledger, The Flag Plant, "flagged for research" for a number you would need but do not have (never invent one). NFL comparisons: at most one in the whole annual, and only if it illuminates; otherwise Pate State role language ("The Trigger", "The Voice"). First person is Josh's; the reader only ever perceives Josh. Sentence case in headlines and labels; no exclamation points; no "X isn't Y, it's Z"; no sentence announcing what a future game "will show" — say what you will be watching for and on what date.

WHAT YOU KNOW ABOUT GEORGIA (use it; cite nothing that is not here):
${FACTS}

REPORTING SOURCES (quotes may be used verbatim with attribution; the facts are yours, the sentences are not):
${SOURCES}

THE REGISTER EXEMPLAR — Josh's Ohio State capsule (structure and voice only; do not reuse its sentences, its jokes, or its stats):
${EXEMPLAR}

Return JSON only, matching the schema. Prose fields are plain text (no markdown) unless the field says otherwise. Every prose paragraph is a single paragraph.`;

// ------------------------------------------------------------ the sections
const P = (n: number) => ({ type: "array", items: S, minItems: n, maxItems: n });
const sections: { id: string; brief: string; schema: unknown; maxTokens?: number }[] = [
  { id: "opener", maxTokens: 6000, brief: `THE OPENER AND THE VERDICT (pages 1–2 of the capsule). Georgia's cover line, the dek (a bold clause then two sentences), the number rail (four numbers that ARE the season: each a verified figure with a one-line label that argues), a hero-art caption, then the Verdict grid of nine cards (The JP Poll · The Pate State Model · Josh's Record · The SEC · The Playoff · Championship Ceiling · The Linchpin · The Biggest Risk · The Flag Plant), three questions the season answers, and Josh Says vs The Model Says (rank, projected record, playoff yes/no, four one-line arguments each, and the crown line). Josh's record here must equal the season pick you will make in the Road section: decide it now and keep it. The Model's record is the site's power ratings — express it as a projected win range and CFP likelihood in the Model's voice (mark it as the Model's number; if you cannot support a precise simulation figure, say "flagged for research" in the small text rather than inventing one).`,
    schema: obj({ coverLine: S, dekBold: S, dekRest: S, numrail: arr(obj({ v: S, l: S })), heroCaption: S, verdictTag: S, cards: arr(obj({ k: S, v: S, s: S, tone: { type: "string", enum: ["plain", "green", "gray"] } })), questions: P(3), joshSays: obj({ rank: S, small: S, bullets: P(4), crown: S, crownYes: { type: "boolean" } }), modelSays: obj({ rank: S, small: S, bullets: P(4), crown: S, crownYes: { type: "boolean" } }), joshRecord: S }) },
  { id: "autopsy", maxTokens: 7000, brief: `THE AUTOPSY. Why 2025 ended (the 24-21 home loss to Alabama on Sept. 27; the 39-34 Sugar Bowl loss to Ole Miss on Jan. 2 in the quarterfinal — after winning the SEC title 28-7 over Alabama on Dec. 6) and what the offseason answered. A lead paragraph, then four to five paragraphs that argue from the numbers (the offense's explosiveness problem the sources document — 55th in 20-plus-yard plays, outside the top 50 in total offense, play-action, third in time of possession; the two losses; the draft and portal turnover; who came back). A photo caption for the defining night, a pull quote that is the thesis of the annual (in Josh's words, with an attribution line), the "why 2025 ended" split (two sides, one number each, and a VS), a trio of numbers, then the rebuild by the numbers: three OUT figures and three IN figures with one-line labels, and a fineprint line for anything flagged for research.`,
    schema: obj({ title: S, tag: S, lead: S, paragraphs: { type: "array", items: S, minItems: 4, maxItems: 5 }, photoTitle: S, photoSub: S, photoCaptionBold: S, photoCaption: S, pullQuote: S, pullAttr: S, whyTitle: S, whyTag: S, sideA: obj({ label: S, value: S, sub: S }), sideB: obj({ label: S, value: S, sub: S }), trio: arr(obj({ v: S, l: S, bad: { type: "boolean" } })), rebuildTag: S, out: P(3), outValues: P(3), inn: P(3), inValues: P(3), fineprint: S }) },
  { id: "offense", maxTokens: 8000, brief: `THE OFFENSE — "The Championship Case" page. Stockton's year two (69.7%, 2,894 yards, 24 TD, 5 INT, 462 rushing yards and 10 rushing TD; seventh in the Heisman vote) and the sources' honest question (the gap between his ceiling and his floor; play-action; who catches the ball now that six of the top seven pass catchers are gone — Branch's 81 catches, Delp, Young, Bell, Thomas); the Mike Bobo question as the sources frame it (fourth-year coordinator, the scrutiny, Smart's defense of him — use Smart's quote); the running backs (Frazier 947 yards, Bowens 526, Dowdell's status); the tight end room as the answer (Luckie, Williams, Reddell, Barbour); the line (Greene, Glover, Bobo, Gaston + the fifth spot: Helton vs Calhoun vs Uini, Jackson at tackle; Bobo's and Greene's injury history). Write: a lead and four to five paragraphs; a ⏱ Watch This line with a date; a bars block (three rows, a label, a small note and a value each — verified numbers only, e.g. points per game in wins vs the two losses, computed from the game log); a "mechanism diagram" adapted to Georgia (the tight ends as the answer to the receiver question, or the run game setting up play-action): one star node with a note, four ghosted nodes with notes, an arrow line, three beneficiary nodes with notes, and a caption; then the most important position battle (the fifth offensive lineman / where Gaston plays): a photo caption, one paragraph, and three outcome boxes (if it holds / if it doesn't / how you'll know, each with a title and a paragraph).`,
    schema: obj({ title: S, tag: S, lead: S, paragraphs: { type: "array", items: S, minItems: 4, maxItems: 5 }, photoTitle: S, photoSub: S, photoCaptionBold: S, photoCaption: S, watch: S, barsTitle: S, barsTag: S, barsK: S, bars: arr(obj({ label: S, small: S, value: S, good: { type: "boolean" }, pct: N })), gravityTitle: S, gravityTag: S, gravityK: S, star: obj({ name: S, note: S }), ghosted: arr(obj({ name: S, note: S })), arrow: S, beneficiaries: arr(obj({ name: S, note: S })), gravityCaptionBold: S, gravityCaption: S, battleTitle: S, battleTag: S, battlePhotoTitle: S, battlePhotoSub: S, battleParagraph: S, outcomes: arr(obj({ title: S, text: S, tone: { type: "string", enum: ["good", "bad", "plain"] } })) }) },
  { id: "defense", maxTokens: 6000, brief: `THE DEFENSE page. What left (Everette, Allen, Miller, the portal departures: Kelly, Aguero, Modozie, Harris…), what returns (the sources: 16 of the 21 defenders with 150+ snaps; McLeod and Griffin up front; Wilson, Cole and Justin Williams inside; Bolden; Ellis Robinson IV; the safety spot next to Bolden open; Khalil Barnes; the pass rush question — Quintavius Johnson, Chase Linton, new outside linebackers coach Larry Knight; Amaris Williams from Auburn), and the honest number: 19 sacks in 14 games, the 24 points Alabama scored, the 39 Ole Miss scored. A lead and four paragraphs, an art caption, and a four-step clock (date/opponent, one-word stage, a sentence each) that ends at the game that is the final exam.`,
    schema: obj({ title: S, tag: S, lead: S, paragraphs: { type: "array", items: S, minItems: 3, maxItems: 4 }, artTitle: S, artSub: S, artCaptionBold: S, artCaption: S, clockTitle: S, clockTag: S, clock: arr(obj({ when: S, stage: S, text: S })) }) },
  { id: "marquee", maxTokens: 9000, brief: `THE MARQUEE — two full profiles (choose the two players the thesis leans on most; Stockton is one) and then the supporting cast: four quarter-page offensive profiles and four defensive ones, then "the rest of the cast" — eight names with one line each, and the fineprint about comparisons. Full profile fields: jersey number if the roster carries it (else ""), role line ("QB · Sr. · The Front Seat"), name, the Pate State rank line, the 2025 stat line (verified numbers only), one paragraph, strengths, the Fair-Witness Flaw, a comp/bottom-line block (label + text), grade chip, watch line. Quarter profiles: role, name, meta line, one paragraph that uses bold labels written as **Strength:** **The question:** **The stake:** inline, grade chip, watch line. Role names are Pate State role language, not NFL comps.`,
    schema: obj({ tag: S, full: arr(obj({ jersey: S, role: S, name: S, rank: S, statline: S, paragraph: S, strengths: S, flaw: S, compLabel: S, comp: S, grade: S, watch: S })), offenseTitle: S, offenseTag: S, offense: arr(obj({ role: S, name: S, meta: S, p: S, grade: S, watch: S })), defenseTitle: S, defenseTag: S, defense: arr(obj({ role: S, name: S, meta: S, p: S, grade: S, watch: S })), castTag: S, cast: arr(obj({ small: S, name: S, p: S })), fineprint: S }) },
  { id: "depth", maxTokens: 7000, brief: `THE PROJECTED 22, the unit grades and the film room. Offense: the eight-man spread row (WR, LT, LG, C, RG, RT, TE, WR), a slot/third receiver row, QB, RB; Defense: four DBs, the Star/nickel, three linebackers, four down linemen — each with position, name and status (lock = locked returner, new = proven newcomer, lead = leader being pushed, battle = open battle). Six key backups (position · name, small note). Twelve unit grades (QB RB WR TE OL DL LB CB S ST Coach Depth) with hi/lo marks, two summary lines (offense, defense), four positions to watch (label + sentence). Then the film room: four numbered blueprints for how opponents attack Georgia (title, show → bring, a sentence), what breaks the blueprint, and the falsifiable inputs: four "move me up" and four "move me down" lines. Depth-chart placements must come from the sources (the depth-chart reporting); if the sources disagree, choose and say "battle".`,
    schema: obj({ tag: S, offenseSpread: arr(obj({ pos: S, name: S, status: { type: "string", enum: ["lock", "new", "lead", "battle"] } })), slot: obj({ pos: S, name: S, status: { type: "string", enum: ["lock", "new", "lead", "battle"] } }), qb: obj({ pos: S, name: S, status: { type: "string", enum: ["lock", "new", "lead", "battle"] } }), rb: obj({ pos: S, name: S, status: { type: "string", enum: ["lock", "new", "lead", "battle"] } }), dbs: arr(obj({ pos: S, name: S, status: { type: "string", enum: ["lock", "new", "lead", "battle"] } })), nickel: obj({ pos: S, name: S, status: { type: "string", enum: ["lock", "new", "lead", "battle"] } }), lbs: arr(obj({ pos: S, name: S, status: { type: "string", enum: ["lock", "new", "lead", "battle"] } })), dl: arr(obj({ pos: S, name: S, status: { type: "string", enum: ["lock", "new", "lead", "battle"] } })), backups: arr(obj({ who: S, note: S })), gradesTag: S, grades: arr(obj({ unit: S, grade: S, mark: { type: "string", enum: ["hi", "lo", "mid"] } })), gsumOffense: S, gsumDefense: S, watch4: arr(obj({ label: S, text: S })), filmTitle: S, filmTag: S, blueprints: arr(obj({ title: S, show: S, bring: S, text: S })), breaks: S, changeTitle: S, changeTag: S, upTitle: S, up: P(4), downTitle: S, down: P(4) }) },
  { id: "road", maxTokens: 9000, brief: `THE ROAD, THE LEDGER AND THE FLAG PLANT. An intro paragraph on the schedule's shape (Tennessee State, Western Kentucky, at Arkansas Sept. 19, Oklahoma Sept. 26, Vanderbilt, at Alabama Oct. 10, Auburn, Florida in Atlanta Oct. 31, at Ole Miss Nov. 7, Missouri, at South Carolina Nov. 21, Georgia Tech Nov. 28 — use the fact sheet's dates; there is one bye, Oct. 24). Every game: date, opponent as "vs X" or "at X", tag (Expected Win, Should Win, Upset Watch, Season-Definer, or ""), pick W or L, one line. Include the bye as a row with pick "—". A stress map with three entries (label, a rating out of 10 where you can justify it or "", text). The Four That Decide It: four games (date · place, opponent, a title, a sentence). The season call line (record · SEC title game · CFP). Then the Ledger rows (date, opponent with ★ for definers and ▲ for upset watch, TV/time as "TBA", pick) and its projected line. Then Five Things That Are Actually True (title + paragraph each), The Margins (four: label, the big number, a title, a paragraph, a watch line), and THE FLAG PLANT: the closing verdict, four to six paragraphs in Josh's first person, the record, the floor and the ceiling, what would make him wrong, signed "— JP". The record must equal the Verdict's joshRecord.`,
    schema: obj({ intro: S, games: arr(obj({ date: S, opp: S, tag: S, pick: S, note: S })), stress: arr(obj({ label: S, rating: S, text: S })), fourTitle: S, four: arr(obj({ when: S, opp: S, title: S, text: S })), seasonCall: S, ledgerRows: arr(obj({ date: S, opp: S, tv: S, pick: S })), ledgerLine: S, trueTitle: S, trueTag: S, fiveTrue: arr(obj({ title: S, text: S })), marginsTag: S, margins: arr(obj({ label: S, big: S, title: S, text: S, watch: S })), flagTitle: S, flagTag: S, flag: { type: "array", items: S, minItems: 4, maxItems: 6 }, record: S, floor: S, ceiling: S }) },
];

const EDIT = `You are the desk editor for The Pate State Preseason Annual, editing a section written under Josh Pate's byline. Keep the JSON shape exactly. You may cut, reorder, combine and rewrite sentences; you may not add a fact, a name or a number that is not in the section. Do: make every lead a built sentence with a number in it; pair numbers so they argue; cut any sentence that explains normal football to a fan; cut any sentence that announces its own analysis ("here's the thing", "the real test is", "will show whether"); cut "X isn't Y, it's Z" pivots and doubled intensifiers; keep one characterization per paragraph, plain words, no abstractions (ceiling is allowed only as the house term "Championship Ceiling"); keep the rhythm uneven — one-sentence paragraphs next to long ones; keep contractions and Josh's directness; sentence case in every label and title; at most one NFL comparison; nothing sounds quotable on purpose. Return the edited JSON only.`;

const flat = (o: unknown): string => typeof o === "string" ? o : Array.isArray(o) ? o.map(flat).join("\n") : o && typeof o === "object" ? Object.values(o as Record<string, unknown>).map(flat).join("\n") : String(o ?? "");
let total = 0;
for (const sec of sections) {
  if (ONLY.length && !ONLY.includes(sec.id)) continue;
  const t0 = Date.now();
  const w = await callJSON<any>({ stage: `annual-${sec.id}`, role: "joshColumnWriter", maxTokens: sec.maxTokens ?? 6000, schemaName: `annual_${sec.id}`, schema: sec.schema as Record<string, unknown>, system: SYSTEM, user: `${dateLine()}\n\nSECTION TO WRITE: ${sec.brief}` });
  total += w.call.costUsd;
  const e = await callJSON<any>({ stage: `annual-${sec.id}-edit`, role: "joshProseEdit", choice: { ...modelForRole("joshProseEdit"), effort: "medium" }, maxTokens: sec.maxTokens ?? 6000, schemaName: `annual_${sec.id}`, schema: sec.schema as Record<string, unknown>, system: EDIT, user: `THE SECTION (JSON):\n${JSON.stringify(w.data, null, 1)}` });
  total += e.call.costUsd;
  const fc = await factCheckSources({ headline: `Georgia 2026 annual — ${sec.id}`, dek: "", bodyMarkdown: flat(e.data), pullQuote: "", primaryTeam: "georgia", teams: ["georgia"], tags: [], seo: { title: "", description: "" } }, `${FACTS}\n\n${SOURCES}`);
  const flagged = fc.result.claims.filter((c) => c.status === "unsupported" || c.status === "contradicted");
  writeFileSync(`${D}/out/${sec.id}.json`, JSON.stringify({ draft: w.data, edited: e.data, fact: fc.result, models: { writer: w.call.model, editor: e.call.model } }, null, 1));
  console.log(`${sec.id}: written by ${w.call.model} (${w.call.outputTokens} tok) · edited by ${e.call.model} · fact ${fc.result.verdict} (${flagged.length} flagged) · ${Math.round((Date.now() - t0) / 1000)}s · $${total.toFixed(2)} so far`);
  for (const f of flagged.slice(0, 6)) console.log(`   ${f.status}: ${f.claim.slice(0, 140)}`);
}
console.log(`DONE $${total.toFixed(2)}`);
