// Build a Pate State Preseason Annual (the Team Capsule) for one team with the
// Sol pipeline (2026-08-30, Isaac: "put the top 5 teams' preseason guides in
// their place"). Fact pack from CFBD + the site's fact sheet + harvested
// reporting; Sol writes each section; Terra edits; the fact checker grades;
// the page is poured into the Ohio State reference build's chrome.
//   npx tsx scripts/annual-build.mts <slug> [--only section,section] [--render-only]
import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync } from "node:fs";
for (const l of readFileSync(".env.local", "utf8").split("\n")) { const i = l.indexOf("="); if (i > 0 && !l.startsWith("#")) process.env[l.slice(0, i).trim()] ??= l.slice(i + 1).trim(); }
const arg = (k: string) => { const i = process.argv.indexOf(k); return i !== -1 ? process.argv[i + 1] : undefined; };
const SLUG = process.argv[2]; const ONLY = (arg("--only") ?? "").split(",").filter(Boolean); const RENDER_ONLY = process.argv.includes("--render-only"); const REPAIR = process.argv.includes("--repair"); const SCRUB = process.argv.includes("--scrub");

interface TeamConfig { slug: string; cfbd: string; name: string; h1: string; no: string; conf: string; colors: [string, string, string]; seed: number; model: string; jpPoll: string; roadTitle: string; titleGame: string; onRecord: string; consistency: string; sources: string[] }
const TEAMS: Record<string, TeamConfig> = {
  clemson: { slug: "clemson", cfbd: "Clemson", name: "Clemson", h1: "Clem<em>son</em>", no: "03", conf: "ACC", colors: ["#F56600", "#C24E00", "#3A1400"], seed: 3, model: "No. 20", jpPoll: "No. 3 seed in Josh's bracket", roadTitle: "The Road to Charlotte", titleGame: "ACC title game",
    onRecord: `- Josh's published 12-team bracket (Aug. 19): Clemson the No. 3 seed with a first-round bye — his third-ranked team in the field. Champion Georgia (31–28 over Ohio State); Clemson loses in the playoff.\n- The Pate State Model: Clemson No. 20 — a 17-spot gap between Josh's board and the machine, the widest in the field. The annual must confront that gap honestly.\n- JP Rating: not on record for Clemson ("flagged for research").`,
    consistency: `No other annual on the site picks a Clemson game yet. Clemson opens at LSU on Sept. 5 (Josh's bracket has LSU the No. 8 seed).`,
    sources: ["https://sports.yahoo.com/articles/clemson-football-2026-tigers-season-130500822.html", "https://sports.yahoo.com/articles/dabo-swinney-says-clemson-bunch-020645722.html", "https://www.si.com/college/clemson/football/dabo-swinney-trust-clemson-tigers-2026", "https://sports.yahoo.com/articles/clemson-hc-dabo-swinney-admits-160439435.html", "https://www.cbssports.com/college-football/news/dabo-swinney-clemson-coaching-staff-overhaul-2026/", "https://sports.yahoo.com/articles/dabo-swinney-stakes-season-clemson-090324370.html", "https://sports.yahoo.com/articles/summer-scheming-26-clemson-tigers-120000427.html", "https://sports.yahoo.com/articles/clemson-hc-dabo-swinney-gets-134800658.html"] },
  "boise-state": { slug: "boise-state", cfbd: "Boise State", name: "Boise State", h1: "Boise <em>State</em>", no: "04", conf: "Pac-12", colors: ["#0033A0", "#002A80", "#001238"], seed: 4, model: "not in the Model's top 25", jpPoll: "No. 4 seed in Josh's bracket", roadTitle: "The Road to the Pac-12 title", titleGame: "Pac-12 title game",
    onRecord: `- Josh's published 12-team bracket (Aug. 19): Boise State the No. 4 seed with a first-round bye — the Group of Six's highest seed and Josh's fourth-ranked team. Champion Georgia; Boise State loses in the playoff.\n- The Pate State Model does not rank Boise State in its preseason top 25. The annual must confront that gap honestly.\n- JP Rating: not on record for Boise State ("flagged for research").`,
    consistency: `No other annual picks a Boise State game. Boise State opens at Oregon on Sept. 5 (Josh's bracket has Oregon the No. 6 seed).`,
    sources: ["https://www.si.com/college/boise-state/football/final-preseason-depth-chart-projection-for-boise-state-football-in-2026", "https://www.si.com/college/boise-state/football/projecting-boise-state-depth-chart-for-week-1-of-2026-college-football-season", "https://www.si.com/college/boise-state/football/where-seven-position-battles-stand-entering-boise-state-2026-season-opener-against-oregon-ducks", "https://www.si.com/college/boise-state/football/boise-state-2026-spring-football-quarterbacks-preview", "https://sports.yahoo.com/articles/boise-states-depth-chart-looks-153607259.html"] },
  texas: { slug: "texas", cfbd: "Texas", name: "Texas", h1: "Tex<em>as</em>", no: "05", conf: "SEC", colors: ["#BF5700", "#9A4600", "#3E1C00"], seed: 5, model: "No. 6", jpPoll: "No. 5 seed in Josh's bracket", roadTitle: "The Road to Atlanta", titleGame: "SEC title game",
    onRecord: `- Josh's published 12-team bracket (Aug. 19): Texas the No. 5 seed, hosting a first-round game — his fifth-ranked team. Champion Georgia; Texas loses in the playoff.\n- The Pate State Model: Texas No. 6.\n- JP Rating: not on record for Texas ("flagged for research").`,
    consistency: `Josh's Ohio State annual (Aug. 18) picks Ohio State to LOSE at Texas on Sept. 12 — so this annual must pick Texas to beat Ohio State on Sept. 12 in Austin. Josh's Georgia annual picks Georgia to win the SEC title game and the national title; Texas does not play Georgia in the regular season.`,
    sources: ["https://www.statesman.com/sports/college/longhorns/football/article/texas-football-2026-roster-22371524.php", "https://www.si.com/college/texas/football/here-is-what-the-texas-longhorns-offensive-depth-chart-could-look-like-in-2026", "https://www.si.com/college/texas/football/texas-longhorns-offensive-line-taking-shape-as-fall-camp-continues", "https://www.si.com/college/texas/football/texas-longhorns-biggest-remaining-position-battles-heading-into-season", "https://www.si.com/college/texas/football/projecting-the-post-spring-2026-texas-longhorns-defensive-depth-chart", "https://www.si.com/college/texas/football/texas-not-shying-away-from-massive-expectations-facing-arch-manning-in-2026", "https://www.si.com/college/texas/football/4-texas-longhorns-climbing-up-depth-chart-during-fall-camp"] },
};
const T = TEAMS[SLUG]; if (!T) throw new Error(`unknown team ${SLUG}; known: ${Object.keys(TEAMS).join(", ")}`);
const D = `.superpowers/annual/${T.slug}`; mkdirSync(`${D}/out`, { recursive: true }); mkdirSync(`${D}/sources`, { recursive: true });
const { callJSON, modelForRole } = await import("../lib/editorial-v3/models.ts");
const { S, N, arr, obj, v3Prompt, dateLine } = await import("../lib/editorial-v3/v3-context.ts");
const { factCheckSources } = await import("../lib/editorial-v3/fact-check.ts");
const { extractArticleText } = await import("../lib/editorial-v3/source-text.ts");
const { teamFactSheet } = await import("../lib/fact-sheet.ts");
const { rosterNames } = await import("../lib/editorial-v3/roster.ts");

// ------------------------------------------------------------ data + sources
if (!RENDER_ONLY) {
  if (!existsSync(`${D}/data.json`)) {
    const H = { authorization: `Bearer ${process.env.CFBD_API_KEY}` };
    const get = async (p: string) => { const r = await fetch(`https://api.collegefootballdata.com${p}`, { headers: H }); return r.ok ? r.json() : []; };
    const q = encodeURIComponent(T.cfbd);
    const data: Record<string, unknown> = { factSheet: await teamFactSheet([T.slug], { games: 14 }), roster: await rosterNames([T.slug]) };
    data.returning = ((await get(`/player/returning?year=2026&team=${q}`)) as any[])[0] ?? {};
    data.stats2025 = await get(`/stats/season?year=2025&team=${q}`);
    data.draft2026 = ((await get(`/draft/picks?year=2026`)) as any[]).filter((p) => (p.collegeTeam ?? "") === T.cfbd);
    data.portal = ((await get(`/player/portal?year=2026`)) as any[]).filter((p) => p.origin === T.cfbd || p.destination === T.cfbd);
    data.games2026 = await get(`/games?year=2026&team=${q}`); data.games2025 = await get(`/games?year=2025&team=${q}`);
    data.recruiting = ((await get(`/recruiting/teams?year=2026`)) as any[]).find((r) => r.team === T.cfbd) ?? {};
    data.talent = ((await get(`/talent?year=2026`)) as any[]).find((r) => r.team === T.cfbd) ?? {};
    const rows = (await get(`/stats/player/season?year=2025&team=${q}`)) as { player: string; category: string; statType: string; stat: string }[];
    const by: Record<string, Record<string, string>> = {}; for (const r of rows) { const k = `${r.player}|${r.category}`; by[k] ??= {}; by[k][r.statType] = r.stat; }
    data.players = Object.entries(by).filter(([k]) => /\|(passing|rushing|receiving|defensive|interceptions|kicking)$/.test(k)).map(([k, v]) => { const [p, c] = k.split("|"); return `${c.padEnd(13)} ${p.padEnd(24)} ${Object.entries(v).map(([a, b]) => `${a}=${b}`).join(" ")}`; }).filter((l) => !/(REC=[1-9]\b|CAR=[1-9]\b|ATT=[1-9]\b|TOT=[1-9]\b)/.test(l)).sort();
    writeFileSync(`${D}/data.json`, JSON.stringify(data, null, 1)); console.log("data pulled");
  }
  if (readdirSync(`${D}/sources`).length === 0) {
    for (const url of T.sources) {
      try { const res = await fetch(url, { headers: { "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36", accept: "text/html" }, signal: AbortSignal.timeout(20000) }); const html = await res.text(); const title = (html.match(/<title>([\s\S]*?)<\/title>/i)?.[1] ?? "").replace(/\s+/g, " ").trim(); const text = extractArticleText(html, 30000); if (text.split(/\s+/).length > 120) writeFileSync(`${D}/sources/${url.replace(/https?:\/\/(www\.)?/, "").replace(/[^a-z0-9]+/gi, "-").slice(0, 70)}.txt`, `URL: ${url}\nTITLE: ${title}\n\n${text}`); console.log(`  source ${res.status} ${text.split(/\s+/).length}w ${title.slice(0, 60)}`); } catch (e) { console.log("  source ERR", url); }
    }
  }
}
const data = JSON.parse(readFileSync(`${D}/data.json`, "utf8"));
const g25 = (data.games2025 as any[]).map((g) => { const home = g.homeTeam === T.cfbd; const us = home ? g.homePoints : g.awayPoints, them = home ? g.awayPoints : g.homePoints; return { date: g.startDate.slice(0, 10), opp: home ? g.awayTeam : g.homeTeam, home, us, them, w: us > them, notes: g.notes ?? "" }; }).filter((g) => g.us != null);
const pf = g25.reduce((a, g) => a + g.us, 0), pa = g25.reduce((a, g) => a + g.them, 0), n25 = g25.length || 1;
const stat = (k: string) => (data.stats2025 as any[]).find((s) => s.statName === k)?.statValue;
const ret = data.returning ?? {};
const pct = (x: unknown) => typeof x === "number" ? `${(x * 100).toFixed(1)}%` : "flagged for research";
const FACTS = `VERIFIED TEAM FACTS — ${T.name.toUpperCase()}, as of ${new Date().toDateString()} (CFBD feed + the site's fact sheet). Never contradict these; never go beyond them without a source below.

${data.factSheet}

2025 RESULTS (${g25.filter((g) => g.w).length}-${g25.filter((g) => !g.w).length}; points for ${pf} / against ${pa} in ${n25} games = ${(pf / n25).toFixed(1)} scored, ${(pa / n25).toFixed(1)} allowed per game):
${g25.map((g) => `  ${g.date} ${g.home ? "vs" : "at"} ${g.opp} ${g.us}-${g.them} ${g.w ? "W" : "L"}${g.notes ? " — " + g.notes : ""}`).join("\n")}

2025 TEAM STATS (${stat("games")} games): total yards ${stat("totalYards")} (allowed ${stat("totalYardsOpponent")}); net passing ${stat("netPassingYards")} (allowed ${stat("netPassingYardsOpponent")}); rushing ${stat("rushingYards")} on ${stat("rushingAttempts")} carries (allowed ${stat("rushingYardsOpponent")}); passing TD ${stat("passingTDs")}, rushing TD ${stat("rushingTDs")}; sacks ${stat("sacks")} (allowed ${stat("sacksOpponent")}); TFL ${stat("tacklesForLoss")}; interceptions ${stat("interceptions")}, thrown ${stat("passesIntercepted")}; turnovers ${stat("turnovers")} (forced ${stat("turnoversOpponent")}); third downs ${stat("thirdDownConversions")}/${stat("thirdDowns")} (opponents ${stat("thirdDownConversionsOpponent")}/${stat("thirdDownsOpponent")}); first downs ${stat("firstDowns")}; penalties ${stat("penalties")} for ${stat("penaltyYards")} yards; time of possession ${Math.round(Number(stat("possessionTime")) / Number(stat("games") || 13) / 60)} min/game.

2025 PLAYER STATS (CFBD):
${(data.players as string[]).join("\n")}

2026 NFL DRAFT — ${T.name.toUpperCase()} PLAYERS TAKEN (${(data.draft2026 as any[]).length}):
${(data.draft2026 as any[]).map((p) => `  Round ${p.round}, pick ${p.overall}: ${p.name}, ${p.position}`).join("\n") || "  none"}

TRANSFER PORTAL 2026 — IN: ${(data.portal as any[]).filter((p) => p.destination === T.cfbd).map((p) => `${p.firstName} ${p.lastName} (${p.position}, from ${p.origin}${p.stars ? `, ${p.stars}-star` : ""})`).join("; ") || "none listed"}
TRANSFER PORTAL 2026 — OUT: ${(data.portal as any[]).filter((p) => p.origin === T.cfbd).map((p) => `${p.firstName} ${p.lastName} (${p.position}, to ${p.destination ?? "undecided"})`).join("; ") || "none listed"}

RETURNING PRODUCTION (CFBD PPA share, 2026): overall ${pct(ret.percentPPA)} · passing ${pct(ret.percentPassingPPA)} · receiving ${pct(ret.percentReceivingPPA)} · rushing ${pct(ret.percentRushingPPA)}. 2026 recruiting class rank: ${data.recruiting?.rank ? `No. ${data.recruiting.rank}` : "flagged for research"}. Team talent composite 2026: ${data.talent?.talent ?? "flagged for research"}.

${data.roster}

JOSH PATE — ON THE RECORD (the site's live positions; the column is under his byline and must not contradict them):
${T.onRecord}
- The JP Poll's top two are Georgia (No. 1) and Ohio State (No. 2, JP Rating 94.9). The Pate State Model's top two are Ohio State (No. 1) and Georgia (No. 2); the Model crowns Ohio State the most likely champion.
- Josh's Ohio State annual (Aug. 18) called Ohio State's roster "the highest ceiling in America" and projected Ohio State 11–1 with its one loss at Texas on Sept. 12. Josh's Georgia annual projects Georgia 11–1, SEC champion, national champion over Ohio State 31–28.
- CONSISTENCY LEDGER (Constitution §4.4: no game may have two winners anywhere on the site): ${T.consistency} ${T.name} does NOT win the national title in this annual (Georgia does); it may win its conference. Every game pick you make here becomes a logged claim.`;
const SOURCES = readdirSync(`${D}/sources`).map((f) => readFileSync(`${D}/sources/${f}`, "utf8")).join("\n\n=====\n\n");
const EXEMPLAR = readFileSync("docs/content/ohio-state-2026-preseason-annual.md", "utf8").replace(/<!--[\s\S]*?-->/, "").slice(0, 32000);
const VOICE = v3Prompt("josh-column-additive").split("HOW A COLUMN IS BUILT")[0];
const SYSTEM = `You are writing the ${T.name} section of The Pate State Preseason Annual — the "Team Capsule" — under Josh Pate's byline, exactly in the shape of the Ohio State capsule reproduced below (its structure, its devices, its density). This is the annual's gold standard; match its register, never copy its sentences. Ohio State's facts are Ohio State's; every ${T.name} fact comes from the FACT PACK and the SOURCES, nothing else.

${VOICE}

THE ANNUAL'S LAWS: the clock is the calendar — date every event (month + day), measure distance event-to-event, and never anchor to the writing moment ("X days from today", "this week"); the page carries one timestamp in its chrome and the prose must read true in December. numbers everywhere a vague quantifier could live (returning starts, sacks allowed, draft picks lost, rating points). Name the program's riskiest personnel decision plainly as the boldest bet, and say what has to be true for it to work, with a watch date. Market framing, never dunk framing ("the market is too high on", never "overrated"). Every prediction is falsifiable and dated; every game gets a pick. "Fair witness" means the flaw gets named next to the strength. House devices you may use: Fair-Witness Flaw, ⏱ Watch, Grade, The Ledger, The Flag Plant, "flagged for research" for a number you would need but do not have (never invent one). NFL comparisons: at most one in the whole annual, and only if it illuminates; otherwise Pate State role language. First person is Josh's; the reader only ever perceives Josh. Sentence case in headlines and labels; spell out numbers one through nine in prose (numerals in stats, scores and dates); no exclamation points; no "X isn't Y, it's Z"; no sentence announcing what a future game "will show" — say what you will be watching for and on what date.

WHAT YOU KNOW ABOUT ${T.name.toUpperCase()} (use it; cite nothing that is not here):
${FACTS}

REPORTING SOURCES (quotes may be used verbatim with attribution; the facts are yours, the sentences are not):
${SOURCES}

THE REGISTER EXEMPLAR — Josh's Ohio State capsule (structure and voice only; do not reuse its sentences, its jokes, or its stats):
${EXEMPLAR}

Return JSON only, matching the schema. Prose fields are plain text (no markdown) unless the field says otherwise. Every prose paragraph is a single paragraph.`;
const P = (n: number) => ({ type: "array", items: S, minItems: n, maxItems: n });
const ST = { type: "string", enum: ["lock", "new", "lead", "battle"] };
const sections: { id: string; brief: string; schema: unknown; maxTokens?: number }[] = [
  { id: "opener", maxTokens: 6000, brief: `THE OPENER AND THE VERDICT. ${T.name}'s cover line, the dek (a bold clause then two sentences), the number rail (four numbers that ARE the season: each a verified figure with a one-line label that argues), a hero-art caption, then the Verdict grid of nine cards (The JP Poll · The Pate State Model · Josh's Record · The ${T.conf} · The Playoff · Championship Ceiling · The Linchpin · The Biggest Risk · The Flag Plant), three questions the season answers, and Josh Says vs The Model Says (rank/seed, projected record, playoff yes/no, four one-line arguments each, and the crown line — Josh's crown line is "✗" because Georgia is his champion). Josh's record here must equal the season pick you will make in the Road section: decide it now and keep it, consistent with the bracket seed (a No. ${T.seed} seed is a playoff team).`,
    schema: obj({ coverLine: S, dekBold: S, dekRest: S, numrail: arr(obj({ v: S, l: S })), heroCaption: S, verdictTag: S, cards: arr(obj({ k: S, v: S, s: S, tone: { type: "string", enum: ["plain", "green", "gray"] } })), questions: P(3), joshSays: obj({ rank: S, small: S, bullets: P(4), crown: S, crownYes: { type: "boolean" } }), modelSays: obj({ rank: S, small: S, bullets: P(4), crown: S, crownYes: { type: "boolean" } }), joshRecord: S }) },
  { id: "autopsy", maxTokens: 7000, brief: `THE AUTOPSY. Why 2025 ended the way it did (use the game log: every loss with its score and date) and what the offseason answered (the draft and portal turnover, who came back, the staff changes the sources report). A lead paragraph, then four to five paragraphs that argue from the numbers. A photo caption for the defining night, a pull quote that is the thesis of the annual (in Josh's words, with an attribution line), the "why 2025 ended" split (two sides, one number each, and a VS — both numbers verified from the pack), a trio of numbers, then the rebuild by the numbers: three OUT figures and three IN figures with one-line labels, and a fineprint line for anything flagged for research.`,
    schema: obj({ title: S, tag: S, lead: S, paragraphs: { type: "array", items: S, minItems: 4, maxItems: 5 }, photoTitle: S, photoSub: S, photoCaptionBold: S, photoCaption: S, pullQuote: S, pullAttr: S, whyTitle: S, whyTag: S, sideA: obj({ label: S, value: S, sub: S }), sideB: obj({ label: S, value: S, sub: S }), trio: arr(obj({ v: S, l: S, bad: { type: "boolean" } })), rebuildTag: S, out: P(3), outValues: P(3), inn: P(3), inValues: P(3), fineprint: S }) },
  { id: "offense", maxTokens: 8000, brief: `THE OFFENSE — "The Championship Case" page. The quarterback (his verified 2025 line), the sources' honest questions, the coordinator and the play-caller as the sources frame them (use a coach's quote), the backs, the receivers and tight ends, the line and its open spot. Write: a lead and four to five paragraphs; a ⏱ Watch This line with a date; a bars block (three rows: a label, a small note and a value each — verified numbers only, e.g. points per game in wins vs losses computed from the game log); a "mechanism diagram" (one star node with a note, four ghosted nodes with notes, an arrow line, three beneficiary nodes with notes, and a caption) that explains the one offensive mechanism the season depends on; then the most important position battle: a photo caption, one paragraph, and three outcome boxes (if it holds / if it doesn't / how you'll know).`,
    schema: obj({ title: S, tag: S, lead: S, paragraphs: { type: "array", items: S, minItems: 4, maxItems: 5 }, photoTitle: S, photoSub: S, photoCaptionBold: S, photoCaption: S, watch: S, barsTitle: S, barsTag: S, barsK: S, bars: arr(obj({ label: S, small: S, value: S, good: { type: "boolean" }, pct: N })), gravityTitle: S, gravityTag: S, gravityK: S, star: obj({ name: S, note: S }), ghosted: arr(obj({ name: S, note: S })), arrow: S, beneficiaries: arr(obj({ name: S, note: S })), gravityCaptionBold: S, gravityCaption: S, battleTitle: S, battleTag: S, battlePhotoTitle: S, battlePhotoSub: S, battleParagraph: S, outcomes: arr(obj({ title: S, text: S, tone: { type: "string", enum: ["good", "bad", "plain"] } })) }) },
  { id: "defense", maxTokens: 6000, brief: `THE DEFENSE page. What left, what returns, what arrived (the sources' depth-chart reporting; the pack's portal list and draft picks), and the honest numbers from the pack (sacks, points allowed, the losses). A lead and three to four paragraphs, an art caption, and a four-step clock (date/opponent, one-word stage, a sentence each) that ends at the game that is the final exam.`,
    schema: obj({ title: S, tag: S, lead: S, paragraphs: { type: "array", items: S, minItems: 3, maxItems: 4 }, artTitle: S, artSub: S, artCaptionBold: S, artCaption: S, clockTitle: S, clockTag: S, clock: arr(obj({ when: S, stage: S, text: S })) }) },
  { id: "marquee", maxTokens: 9000, brief: `THE MARQUEE — two full profiles (the two players the thesis leans on most) and then the supporting cast: four quarter-page offensive profiles and four defensive ones, then "the rest of the cast" — eight names with one line each, and the fineprint about comparisons. Full profile fields: jersey number if the roster carries it (else ""), role line ("QB · Sr. · The Trigger"), name, the Pate State rank line, the 2025 stat line (verified numbers only; a newcomer's line from the sources or "flagged for research"), one paragraph, strengths, the Fair-Witness Flaw, a comp/bottom-line block (label + text), grade chip, watch line. Quarter profiles: role, name, meta line, one paragraph using bold labels written as **Strength:** **The question:** **The stake:** inline, grade chip, watch line. Names must come from the roster block or the sources.`,
    schema: obj({ tag: S, full: arr(obj({ jersey: S, role: S, name: S, rank: S, statline: S, paragraph: S, strengths: S, flaw: S, compLabel: S, comp: S, grade: S, watch: S })), offenseTitle: S, offenseTag: S, offense: arr(obj({ role: S, name: S, meta: S, p: S, grade: S, watch: S })), defenseTitle: S, defenseTag: S, defense: arr(obj({ role: S, name: S, meta: S, p: S, grade: S, watch: S })), castTag: S, cast: arr(obj({ small: S, name: S, p: S })), fineprint: S }) },
  { id: "depth", maxTokens: 7000, brief: `THE PROJECTED 22, the unit grades and the film room. Offense: the eight-man spread row (WR, LT, LG, C, RG, RT, TE, WR), a slot/third receiver row, QB, RB; Defense: four DBs, the nickel, three linebackers (or two, if the sources describe a four-down front with two — then put the third as a hybrid), four down linemen — each with position, name and status (lock = locked returner, new = proven newcomer, lead = leader being pushed, battle = open battle). Six key backups (position · name, small note). Twelve unit grades (QB RB WR TE OL DL LB CB S ST Coach Depth) with hi/lo marks, two summary lines, four positions to watch. Then the film room: four numbered blueprints for how opponents attack ${T.name} (title, show → bring, a sentence), what breaks the blueprint, and the falsifiable inputs: four "move me up" and four "move me down" lines. Placements come from the sources; if they disagree, choose and say "battle".`,
    schema: obj({ tag: S, offenseSpread: arr(obj({ pos: S, name: S, status: ST })), slot: obj({ pos: S, name: S, status: ST }), qb: obj({ pos: S, name: S, status: ST }), rb: obj({ pos: S, name: S, status: ST }), dbs: arr(obj({ pos: S, name: S, status: ST })), nickel: obj({ pos: S, name: S, status: ST }), lbs: arr(obj({ pos: S, name: S, status: ST })), dl: arr(obj({ pos: S, name: S, status: ST })), backups: arr(obj({ who: S, note: S })), gradesTag: S, grades: arr(obj({ unit: S, grade: S, mark: { type: "string", enum: ["hi", "lo", "mid"] } })), gsumOffense: S, gsumDefense: S, watch4: arr(obj({ label: S, text: S })), filmTitle: S, filmTag: S, blueprints: arr(obj({ title: S, show: S, bring: S, text: S })), breaks: S, changeTitle: S, changeTag: S, upTitle: S, up: P(4), downTitle: S, down: P(4) }) },
  { id: "road", maxTokens: 9000, brief: `THE ROAD, THE LEDGER AND THE FLAG PLANT. An intro paragraph on the schedule's shape (use the fact sheet's 2026 schedule and dates exactly; include the bye week(s) as rows with pick "—"). Every game: date (like "SEP 5"), opponent as "vs X" or "at X", tag (Expected Win, Should Win, Upset Watch, Season-Definer, or ""), pick W or L, one line. A stress map with three entries (label, a rating out of 10 where you can justify it or "", text). The Four That Decide It: four games (date · place, opponent, a title, a sentence). The season call line (record · ${T.titleGame} · CFP seed). Then the Ledger rows (date, opponent with ★ for definers and ▲ for upset watch, TV/time as "TBA", pick) and its projected line. Then Five Things That Are Actually True (title + paragraph each), The Margins (four: label, the big number, a title, a paragraph, a watch line), and THE FLAG PLANT: the closing verdict, four to six paragraphs in Josh's first person, the record, the floor and the ceiling, what would make him wrong, signed "— JP". The record must equal the Verdict's joshRecord. Respect the consistency ledger in the fact pack.`,
    schema: obj({ intro: S, games: arr(obj({ date: S, opp: S, tag: S, pick: S, note: S })), stress: arr(obj({ label: S, rating: S, text: S })), fourTitle: S, four: arr(obj({ when: S, opp: S, title: S, text: S })), seasonCall: S, ledgerRows: arr(obj({ date: S, opp: S, tv: S, pick: S })), ledgerLine: S, trueTitle: S, trueTag: S, fiveTrue: arr(obj({ title: S, text: S })), marginsTag: S, margins: arr(obj({ label: S, big: S, title: S, text: S, watch: S })), flagTitle: S, flagTag: S, flag: { type: "array", items: S, minItems: 4, maxItems: 6 }, record: S, floor: S, ceiling: S }) },
];
const EDIT = `You are the desk editor for The Pate State Preseason Annual, editing a section written under Josh Pate's byline. Keep the JSON shape exactly. You may cut, reorder, combine and rewrite sentences; you may not add a fact, a name or a number that is not in the section. Do: make every lead a built sentence with a number in it; pair numbers so they argue; cut any sentence that explains normal football to a fan; cut any sentence that announces its own analysis ("here's the thing", "the real test is", "will show whether"); cut "X isn't Y, it's Z" pivots and doubled intensifiers; keep one characterization per paragraph, plain words, no abstractions (ceiling is allowed only as the house term "Championship Ceiling"); keep the rhythm uneven — one-sentence paragraphs next to long ones; keep contractions and Josh's directness; spell out one through nine in prose (numerals stay in stats, scores, dates and labels); sentence case in every label and title; at most one NFL comparison; nothing sounds quotable on purpose. Return the edited JSON only.`;
const flat = (o: unknown): string => typeof o === "string" ? o : Array.isArray(o) ? o.map(flat).join("\n") : o && typeof o === "object" ? Object.values(o as Record<string, unknown>).map(flat).join("\n") : String(o ?? "");
if (REPAIR) {
  // Fact repair (2026-08-30): for every section the checker flagged, Terra
  // cuts each flagged claim or replaces its number with "flagged for
  // research" — adding nothing — then the section is re-checked.
  let total = 0;
  for (const sec of sections) {
    const p = `${D}/out/${sec.id}.json`; if (!existsSync(p)) continue;
    const j = JSON.parse(readFileSync(p, "utf8")); const bad = (j.fact?.claims ?? []).filter((c: any) => c.status === "unsupported" || c.status === "contradicted");
    if (!bad.length) continue;
    const r = await callJSON<any>({ stage: `annual-${sec.id}-repair`, role: "joshProseEdit", choice: { ...modelForRole("joshProseEdit"), effort: "medium" }, maxTokens: sec.maxTokens ?? 6000, schemaName: `annual_${sec.id}`, schema: sec.schema as Record<string, unknown>, system: `You are repairing facts in a section of The Pate State Preseason Annual. Keep the JSON shape exactly and change nothing except what the FLAGS require. For each flagged claim: if it is a prediction, a pick, a grade or a projection under Josh's byline, leave it (those are opinions, not facts); if it is a checkable fact the pack does not carry (a transfer's statistics from another school, a jersey number, a height or weight, a coaching-staff fact, a quote, a count), cut the sentence or replace the specific number with the words "flagged for research", keeping the sentence readable; if it is contradicted, correct it ONLY if the correct figure is visible in the evidence, otherwise cut it. Never add a new fact. Return the repaired JSON only.`, user: `FLAGS:\n${bad.map((b: any) => `- [${b.status}] ${b.claim}${b.evidence ? ` (evidence: ${b.evidence})` : ""}`).join("\n")}\n\nTHE SECTION (JSON):\n${JSON.stringify(j.edited, null, 1)}` });
    total += r.call.costUsd;
    const fc = await factCheckSources({ headline: `${T.name} 2026 annual — ${sec.id}`, dek: "", bodyMarkdown: flat(r.data), pullQuote: "", primaryTeam: T.slug, teams: [T.slug], tags: [], seo: { title: "", description: "" } }, `${FACTS}\n\n${SOURCES}`);
    const still = fc.result.claims.filter((c) => c.status === "unsupported" || c.status === "contradicted");
    writeFileSync(p, JSON.stringify({ ...j, edited: r.data, fact: fc.result, repaired: bad.map((b: any) => b.claim) }, null, 1));
    console.log(`${sec.id}: repaired ${bad.length} → still flagged ${still.length} · ${total.toFixed(2)}`);
  }
  console.log(`REPAIRED ${total.toFixed(2)}`);
}
if (SCRUB) {
  // Placeholder scrub (2026-08-30): the repair pass leaves literal "flagged
  // for research" markers in the prose. Before a page ships, Terra removes
  // every marker and rewrites the affected sentence to read naturally
  // without the missing figure — adding nothing.
  let total = 0;
  for (const sec of sections) {
    const p = `${D}/out/${sec.id}.json`; if (!existsSync(p)) continue;
    const j = JSON.parse(readFileSync(p, "utf8")); const txt = JSON.stringify(j.edited);
    if (!/flagged for research|not invented/i.test(txt)) continue;
    const r = await callJSON<any>({ stage: `annual-${sec.id}-scrub`, role: "joshProseEdit", choice: { ...modelForRole("joshProseEdit"), effort: "medium" }, maxTokens: sec.maxTokens ?? 6000, schemaName: `annual_${sec.id}`, schema: sec.schema as Record<string, unknown>, system: `You are cleaning a section of The Pate State Preseason Annual before it publishes. Keep the JSON shape exactly and change nothing except what these rules require. Remove every occurrence of the placeholder phrase "flagged for research" and every sentence whose only content is that a number, rank, role or figure was unavailable, not supplied, not on record or not invented. Rewrite each affected sentence so it reads naturally without the missing figure (example: "Ronan Hanafin returns after flagged for research tackles" becomes "Ronan Hanafin returns"; "his 2025 production is flagged for research" is simply cut). In short label or meta fields drop the placeholder fragment and its separator ("Pate State rank: flagged for research · The anchor" becomes "The anchor"; "Open competition · flagged for research" becomes "Open competition"; "Projected record flagged for research · CFP YES" becomes "CFP YES"); a field left with nothing may be an empty string. Never add a fact, a number, a name, a ranking or a projection. Return the cleaned JSON only.`, user: `THE SECTION (JSON):\n${JSON.stringify(j.edited, null, 1)}` });
    total += r.call.costUsd;
    const left = (JSON.stringify(r.data).match(/flagged for research/gi) ?? []).length;
    writeFileSync(p, JSON.stringify({ ...j, edited: r.data, scrubbed: true }, null, 1));
    console.log(`${sec.id}: scrubbed · ${left} markers left · ${total.toFixed(2)}`);
  }
  console.log(`SCRUBBED ${total.toFixed(2)}`);
}
if (!RENDER_ONLY && !REPAIR && !SCRUB) {
  let total = 0;
  for (const sec of sections) {
    if (ONLY.length && !ONLY.includes(sec.id)) continue;
    if (!ONLY.length && existsSync(`${D}/out/${sec.id}.json`)) { console.log(`${sec.id}: exists, skipping`); continue; }
    const t0 = Date.now();
    let w = await callJSON<any>({ stage: `annual-${sec.id}`, role: "joshColumnWriter", maxTokens: sec.maxTokens ?? 6000, schemaName: `annual_${sec.id}`, schema: sec.schema as Record<string, unknown>, system: SYSTEM, user: `${dateLine()}\n\nSECTION TO WRITE: ${sec.brief}` });
    if (w.call.model !== "gpt-5.6-sol") { console.log(`   ${sec.id}: ${w.call.model} answered; retrying for Sol`); const w2 = await callJSON<any>({ stage: `annual-${sec.id}`, role: "joshColumnWriter", maxTokens: sec.maxTokens ?? 6000, schemaName: `annual_${sec.id}`, schema: sec.schema as Record<string, unknown>, system: SYSTEM, user: `${dateLine()}\n\nSECTION TO WRITE: ${sec.brief}` }); if (w2.call.model === "gpt-5.6-sol") w = w2; }
    total += w.call.costUsd;
    const e = await callJSON<any>({ stage: `annual-${sec.id}-edit`, role: "joshProseEdit", choice: { ...modelForRole("joshProseEdit"), effort: "medium" }, maxTokens: sec.maxTokens ?? 6000, schemaName: `annual_${sec.id}`, schema: sec.schema as Record<string, unknown>, system: EDIT, user: `THE SECTION (JSON):\n${JSON.stringify(w.data, null, 1)}` });
    total += e.call.costUsd;
    const fc = await factCheckSources({ headline: `${T.name} 2026 annual — ${sec.id}`, dek: "", bodyMarkdown: flat(e.data), pullQuote: "", primaryTeam: T.slug, teams: [T.slug], tags: [], seo: { title: "", description: "" } }, `${FACTS}\n\n${SOURCES}`);
    const flagged = fc.result.claims.filter((c) => c.status === "unsupported" || c.status === "contradicted");
    writeFileSync(`${D}/out/${sec.id}.json`, JSON.stringify({ draft: w.data, edited: e.data, fact: fc.result, models: { writer: w.call.model, editor: e.call.model } }, null, 1));
    console.log(`${sec.id}: written by ${w.call.model} · edited by ${e.call.model} · fact ${fc.result.verdict} (${flagged.length} flagged) · ${Math.round((Date.now() - t0) / 1000)}s · $${total.toFixed(2)} so far`);
    for (const f of flagged.slice(0, 5)) console.log(`   ${f.status}: ${f.claim.slice(0, 140)}`);
  }
  console.log(`WRITTEN $${total.toFixed(2)}`);
}

// ------------------------------------------------------------ render
const css = readFileSync(".superpowers/uga-annual/chrome.css", "utf8").replace("--team:#BB0000; --team-dk:#8A0000; --team-deep:#3A0007;", `--team:${T.colors[0]}; --team-dk:${T.colors[1]}; --team-deep:${T.colors[2]};`);
const esc = (s: unknown) => String(s ?? "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
const md = (s: unknown) => esc(s).replace(/\*\*(.+?)\*\*/g, "<b>$1</b>");
const load = (id: string) => { const p = `${D}/out/${id}.json`; return existsSync(p) ? JSON.parse(readFileSync(p, "utf8")).edited : null; };
const op = load("opener"), au = load("autopsy"), of = load("offense"), df = load("defense"), mq = load("marquee"), dp = load("depth"), rd = load("road");
const folio = (title: string, pages: string) => `<div class="folio bottom"><span>${esc(title)}</span><span>${esc(pages)}</span></div>`;
const head = (title: string) => `<div class="folio"><span>No. ${T.no} · ${esc(T.name)}</span><b>${esc(title)}</b></div>`;
const photo = (t: unknown, s: unknown, cls = "photo", label = "Photo slot") => `<div class="${cls}"><i>${label}</i><b>${esc(t)}<small>${esc(s)}</small></b></div>`;
const sub = (h: unknown, tag: unknown) => `<div class="subhead"><h4>${esc(h)}</h4><div class="ln"></div>${tag ? `<span class="tg">${esc(tag)}</span>` : ""}</div>`;
let pn = 1; const pageNo = () => { const a = pn; pn += 2; return `Pages ${a}–${a + 1}`; };
const today = new Date().toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" });
let html = `<title>${esc(T.name)} 2026 — The Pate State Preseason Annual</title>
<link rel="preconnect" href="https://fonts.googleapis.com"><link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed:ital,wght@0,500;0,600;0,700;0,800;1,700&family=Public+Sans:ital,wght@0,400;0,500;0,600;0,700;0,800;1,400;1,600&display=swap" rel="stylesheet">
<style>${css}
.draftnote{max-width:1120px;margin:18px auto 0;padding:12px 18px;background:#1a1a1c;color:#d7d3c8;font:500 13px/1.5 var(--body);border:1px solid #333}.draftnote b{color:#fff}
.fact-flag{background:#FFF4E5;border-left:4px solid #E09A2B;padding:10px 14px;margin:14px 0;font:500 12.5px/1.5 var(--body);color:#5a3d00}</style>
<header class="mast"><div class="in"><a class="logo" href="/">The Pate <em>State</em></a><a class="join" href="/join">Join Free</a></div></header>
<nav class="chapters"><div class="in"><a href="#p1"><b>01</b>Verdict</a><a href="#p2"><b>02</b>Autopsy</a><a href="#p3"><b>03</b>Offense</a><a href="#p4"><b>04</b>Defense</a><a href="#p5"><b>05</b>The Marquee</a><a href="#p8"><b>06</b>Projected 22</a><a href="#p9"><b>07</b>Film Room</a><a href="#p10"><b>08</b>Schedule</a><a href="#p11"><b>09</b>Ledger</a><a href="#p13"><b>10</b>Flag Plant</a></div></nav>
<div class="draftnote"><b>Review draft — produced by the Sol pipeline on ${today}.</b> Written by ChatGPT Sol from a verified fact pack (CFBD, the site's fact sheet, reporting sources), edited by Terra, fact-checked section by section. Photo slots are placeholders, as in the Ohio State reference build.</div>`;
if (op) html += `<section class="page opener dark" id="p1"><div class="folio"><span>The Pate State Preseason Annual · Vol. I</span><b>No. ${T.no} · The Team Capsule</b></div><div class="ghost" aria-hidden="true">${T.no}</div><div class="pin">
<div class="rankline"><span class="chip">${esc(T.jpPoll)}</span><span class="conf">${esc(T.conf)} · 2025: ${g25.filter((g) => g.w).length}–${g25.filter((g) => !g.w).length} · The Model: ${esc(T.model)}</span></div>
<h1>${T.h1}</h1><p class="dek"><b>${esc(op.dekBold)}</b> ${esc(op.dekRest)}</p>
<div class="numrail">${op.numrail.map((n: any) => `<div><div class="v">${esc(n.v)}</div><div class="l">${esc(n.l)}</div></div>`).join("")}</div>
<div class="bystrip">Written by <b>Josh Pate</b> · Charted by the Pate State Database · 90 sec · 8 min · 25 min layers · All picks → <b>The Ledger</b> · Draft of ${today}</div>
<div class="heroph" style="background:linear-gradient(180deg,${T.colors[1]} 0%,${T.colors[2]} 60%,#000 100%)"><i>Pate State original art</i><b>${esc(op.heroCaption)}</b></div></div>${folio(op.coverLine, pageNo())}</section>
<section class="page dark darkpg">${head("The Verdict")}<div class="pin"><div class="spread"><h3>The Verdict</h3><span class="tag">${esc(op.verdictTag)}</span></div>
<div class="vgrid">${op.cards.map((c: any) => `<div class="vc"><div class="k">${esc(c.k)}</div><div class="v${c.tone === "green" ? " g" : c.tone === "gray" ? " gr" : ""}">${esc(c.v)}</div><div class="s">${esc(c.s)}</div></div>`).join("")}</div>
<div class="q3">${op.questions.map((q: string, i: number) => `<div><b>${i + 1}</b>${esc(q)}</div>`).join("")}</div>
<div class="jvm"><div class="col"><h4>Josh Says</h4><div class="big">${esc(op.joshSays.rank)} <small>${esc(op.joshSays.small)}</small></div><ul>${op.joshSays.bullets.map((b: string) => `<li>${esc(b)}</li>`).join("")}</ul><div class="crown${op.joshSays.crownYes ? "" : " no"}">${op.joshSays.crownYes ? "✓" : "✗"} ${esc(op.joshSays.crown)}</div></div><div class="vsmed">VS</div><div class="col"><h4>The Model Says</h4><div class="big">${esc(op.modelSays.rank)} <small>${esc(op.modelSays.small)}</small></div><ul>${op.modelSays.bullets.map((b: string) => `<li>${esc(b)}</li>`).join("")}</ul><div class="crown${op.modelSays.crownYes ? "" : " no"}">${op.modelSays.crownYes ? "✓" : "✗"} ${esc(op.modelSays.crown)}</div></div></div></div>${folio("JP Preseason Annual · 2026", pageNo())}</section>`;
if (au) { const ps = au.paragraphs; html += `<section class="page" id="p2">${head("The Autopsy")}<div class="pin"><div class="spread"><h3>${esc(au.title)}</h3><span class="tag">${esc(au.tag)}</span></div><div class="cols"><p class="lead">${esc(au.lead)}</p>${ps.slice(0, 1).map((p: string) => `<p>${md(p)}</p>`).join("")}<div class="col-photo">${photo(au.photoTitle, au.photoSub, "photo gm")}<div class="cap"><b>${esc(au.photoCaptionBold)}</b> ${esc(au.photoCaption)}</div></div>${ps.slice(1, 3).map((p: string) => `<p>${md(p)}</p>`).join("")}<div class="pullq">${esc(au.pullQuote)}<span class="attr">${esc(au.pullAttr)}</span></div>${ps.slice(3).map((p: string) => `<p>${md(p)}</p>`).join("")}</div>${sub(au.whyTitle, au.whyTag)}<div class="au"><div class="side"><b>${esc(au.sideA.label)}</b><i>${esc(au.sideA.value)}</i><span>${esc(au.sideA.sub)}</span></div><div class="vs">VS</div><div class="side bad"><b>${esc(au.sideB.label)}</b><i>${esc(au.sideB.value)}</i><span>${esc(au.sideB.sub)}</span></div></div><div class="trio">${au.trio.map((t: any) => `<div${t.bad ? ' class="bad"' : ""}><b>${esc(t.v)}</b>${esc(t.l)}</div>`).join("")}</div>${sub("The rebuild, by the numbers", au.rebuildTag)}<div class="turn"><div class="side out"><h4>Out</h4><ul>${au.out.map((o: string, i: number) => `<li><b>${esc(au.outValues[i])}</b>${esc(o)}</li>`).join("")}</ul></div><div class="mid">→</div><div class="side in"><h4>In</h4><ul>${au.inn.map((o: string, i: number) => `<li><b>${esc(au.inValues[i])}</b>${esc(o)}</li>`).join("")}</ul></div></div><p class="fineprint">${esc(au.fineprint)}</p></div>${folio("JP Preseason Annual · 2026", pageNo())}</section>`; }
if (of) { const ps = of.paragraphs; html += `<section class="page" id="p3">${head("The Offense")}<div class="pin"><div class="spread"><h3>${esc(of.title)}</h3><span class="tag">${esc(of.tag)}</span></div><div class="cols"><p class="lead">${esc(of.lead)}</p>${ps.slice(0, 1).map((p: string) => `<p>${md(p)}</p>`).join("")}<div class="col-photo">${photo(of.photoTitle, of.photoSub)}<div class="cap"><b>${esc(of.photoCaptionBold)}</b> ${esc(of.photoCaption)}</div></div>${ps.slice(1).map((p: string) => `<p>${md(p)}</p>`).join("")}</div><span class="watch"><b>⏱ Watch This</b>${esc(of.watch)}</span>${sub(of.barsTitle, of.barsTag)}<div class="bars"><div class="k">${esc(of.barsK)}</div>${of.bars.map((b: any) => `<div class="brow"><b>${esc(b.label)}<small>${esc(b.small)}</small></b><div class="bar"><i class="${b.good ? "good" : "bad"}" style="width:${Math.max(4, Math.min(100, Number(b.pct) || 50))}%"></i></div><span class="v${b.good ? "" : " r"}">${esc(b.value)}</span></div>`).join("")}</div>${sub(of.gravityTitle, of.gravityTag)}<div class="gravity"><div class="k">${esc(of.gravityK)}</div><div class="gfield"><div class="grow2"><span class="gp star">${esc(of.star.name)}<small>${esc(of.star.note)}</small></span>${of.ghosted.map((g: any) => `<span class="gp ghosted">${esc(g.name)}<small>${esc(g.note)}</small></span>`).join("")}</div><div class="garr">${esc(of.arrow)}</div><div class="grow2">${of.beneficiaries.map((g: any) => `<span class="gp">${esc(g.name)}<small>${esc(g.note)}</small></span>`).join("")}</div></div><div class="gcap"><b>${esc(of.gravityCaptionBold)}</b> ${esc(of.gravityCaption)}</div></div>${sub(of.battleTitle, of.battleTag)}<div class="ltb"><div class="ph photo gm"><i>Photo slot</i><b>${esc(of.battlePhotoTitle)}<small>${esc(of.battlePhotoSub)}</small></b></div><div class="bd"><p>${md(of.battleParagraph)}</p>${of.outcomes.map((o: any) => `<div class="oc${o.tone === "good" ? " good" : o.tone === "bad" ? " bad" : ""}"><b>${esc(o.title)}</b><p>${esc(o.text)}</p></div>`).join("")}</div></div></div>${folio("JP Preseason Annual · 2026", pageNo())}</section>`; }
if (df) { const ps = df.paragraphs; html += `<section class="page" id="p4">${head("The Defense")}<div class="pin"><div class="spread"><h3>${esc(df.title)}</h3><span class="tag">${esc(df.tag)}</span></div><div class="cols"><p class="lead">${esc(df.lead)}</p>${ps.slice(0, 1).map((p: string) => `<p>${md(p)}</p>`).join("")}<div class="col-photo">${photo(df.artTitle, df.artSub, "photo gm", "Pate State original art")}<div class="cap"><b>${esc(df.artCaptionBold)}</b> ${esc(df.artCaption)}</div></div>${ps.slice(1).map((p: string) => `<p>${md(p)}</p>`).join("")}</div>${sub(df.clockTitle, df.clockTag)}<div class="clock">${df.clock.map((c: any) => `<div><small>${esc(c.when)}</small><b>${esc(c.stage)}</b><p>${esc(c.text)}</p></div>`).join("")}</div></div>${folio("JP Preseason Annual · 2026", pageNo())}</section>`; }
if (mq) { const prof = (p: any, i: number) => `<div class="prof"><div class="ph photo${i % 2 ? " gm" : ""}">${p.jersey ? `<span class="jersey">${esc(p.jersey)}</span>` : ""}<i>Photo slot</i><b>${esc(p.name)}<small>Game photo</small></b></div><div class="body"><div class="role">${esc(p.role)}</div><h4>${esc(p.name)}</h4><div class="meta">${esc(p.rank)}</div><div class="statline">${esc(p.statline)}</div><p>${md(p.paragraph)}</p><div class="swrow"><div class="s"><b>Strengths</b>${esc(p.strengths)}</div><div class="w"><b>The Fair-Witness Flaw</b>${esc(p.flaw)}</div></div><div class="comp"><b>${esc(p.compLabel)}</b>${esc(p.comp)}</div><div class="foot"><span class="gradechip">${esc(p.grade)}</span><span class="wd">⏱ ${esc(p.watch)}</span></div></div></div>`;
  const qp = (p: any, i: number) => `<div class="qp"><div class="ph photo${i % 2 ? " gm" : ""}"><i>Photo slot</i><b>${esc(p.name)}</b></div><div class="body"><div class="role">${esc(p.role)}</div><h5>${esc(p.name)}</h5><div class="meta">${esc(p.meta)}</div><p>${md(p.p)}</p><div class="foot"><span class="gradechip">${esc(p.grade)}</span><span class="wd">⏱ ${esc(p.watch)}</span></div></div></div>`;
  html += `<section class="page" id="p5">${head("The Marquee · I")}<div class="pin"><div class="spread"><h3>The Marquee</h3><span class="tag">${esc(mq.tag)}</span></div>${mq.full.map(prof).join("")}</div>${folio("JP Preseason Annual · 2026", pageNo())}</section><section class="page" id="p6">${head("The Marquee · II")}<div class="pin"><div class="spread"><h3>${esc(mq.offenseTitle)}</h3><span class="tag">${esc(mq.offenseTag)}</span></div><div class="qgrid">${mq.offense.map(qp).join("")}</div></div>${folio("JP Preseason Annual · 2026", pageNo())}</section><section class="page" id="p7">${head("The Marquee · III")}<div class="pin"><div class="spread"><h3>${esc(mq.defenseTitle)}</h3><span class="tag">${esc(mq.defenseTag)}</span></div><div class="qgrid">${mq.defense.map(qp).join("")}</div>${sub("The rest of the cast", mq.castTag)}<div class="cast">${mq.cast.map((c: any) => `<div><small>${esc(c.small)}</small><h6>${esc(c.name)}</h6><p>${esc(c.p)}</p></div>`).join("")}</div><p class="fineprint">${esc(mq.fineprint)}</p></div>${folio("JP Preseason Annual · 2026", pageNo())}</section>`; }
if (dp) { const fp = (x: any) => `<span class="fp ${x.status}">${esc(x.pos)}<small>${esc(x.name)}</small></span>`;
  html += `<section class="page" id="p8">${head("The Depth Chart")}<div class="pin"><div class="spread"><h3>The Projected 22 — on the field</h3><span class="tag">${esc(dp.tag)}</span></div><div class="fieldwrap"><div class="flab">Offense</div><div class="frow spread-row">${dp.offenseSpread.map(fp).join("")}</div><div class="frow">${fp(dp.slot)}</div><div class="frow">${fp(dp.qb)}</div><div class="frow">${fp(dp.rb)}</div><div class="flab">Defense</div><div class="frow spread-row">${dp.dbs.map(fp).join("")}</div><div class="frow">${fp(dp.nickel)}</div><div class="frow">${dp.lbs.map(fp).join("")}</div><div class="frow">${dp.dl.map(fp).join("")}</div><div class="flegend"><span><i class="lock"></i>Locked returner</span><span><i class="new"></i>Proven newcomer</span><span><i class="lead"></i>Leader, being pushed</span><span><i class="battle"></i>Open battle</span></div></div><div class="backups"><div class="k">The next men up — key backups</div><div class="row">${dp.backups.map((b: any) => `<span>${esc(b.who)}<small>${esc(b.note)}</small></span>`).join("")}</div></div>${sub("The Pate State unit grades", dp.gradesTag)}<div class="gstrip">${dp.grades.map((g: any) => `<div class="gs${g.mark === "hi" ? " hi" : g.mark === "lo" ? " lo" : ""}"><b>${esc(g.unit)}</b><i>${esc(g.grade)}</i></div>`).join("")}</div><div class="gsum"><div>${md(dp.gsumOffense)}</div><div>${md(dp.gsumDefense)}</div></div>${sub("Four positions to watch", "")}<div class="watch4">${dp.watch4.map((w: any) => `<div><b>${esc(w.label)}</b><p>${esc(w.text)}</p></div>`).join("")}</div></div>${folio("JP Preseason Annual · 2026", pageNo())}</section><section class="page" id="p9">${head("The Film Room")}<div class="pin"><div class="spread"><h3>${esc(dp.filmTitle)}</h3><span class="tag">${esc(dp.filmTag)}</span></div><div class="bp">${dp.blueprints.map((b: any, i: number) => `<div class="bpc"><h4><span>${i + 1}</span>${esc(b.title)}</h4><div class="sb"><span class="show">${esc(b.show)}</span><span class="ar">→</span><span class="bring">${esc(b.bring)}</span></div><p>${esc(b.text)}</p></div>`).join("")}</div><div class="breaks"><b>What breaks the blueprint</b>${esc(dp.breaks)}</div>${sub(dp.changeTitle, dp.changeTag)}<div class="flip"><div class="col up"><h4>${esc(dp.upTitle)}</h4><ul>${dp.up.map((u: string) => `<li>${esc(u)}</li>`).join("")}</ul></div><div class="col dn"><h4>${esc(dp.downTitle)}</h4><ul>${dp.down.map((u: string) => `<li>${esc(u)}</li>`).join("")}</ul></div></div></div>${folio("JP Preseason Annual · 2026", pageNo())}</section>`; }
if (rd) { const cls = (t: string) => /definer/i.test(t) ? "r" : /upset/i.test(t) ? "o" : /should/i.test(t) ? "y" : "g";
  html += `<section class="page" id="p10">${head("The Road")}<div class="pin"><div class="spread"><h3>${esc(T.roadTitle)}</h3><span class="tag"><span style="color:#1E7D3E">●</span> Expected Win &nbsp;<span style="color:#b58a00">●</span> Should Win &nbsp;<span style="color:#d2691e">●</span> Upset Watch &nbsp;<span style="color:${T.colors[0]}">●</span> Season-Definer</span></div><div class="cols"><p class="lead">${esc(rd.intro)}</p></div><div class="roadgrid"><div class="road">${rd.games.map((g: any) => `<div class="stop ${g.pick === "—" ? "g" : cls(g.tag)}${/definer/i.test(g.tag) ? " zone" : ""}"><div class="d">${esc(g.date)}${g.tag ? " · " + esc(g.tag) : ""}</div><h5>${esc(g.opp)} ${g.pick === "—" ? "" : `<span class="pick ${String(g.pick).toLowerCase()}">${esc(g.pick)}</span>`}</h5><p>${esc(g.note)}</p></div>`).join("")}</div><aside class="stress"><div class="k">📉 Schedule stress map</div>${rd.stress.map((s: any) => `<div class="sti${s.rating ? " dz" : ""}"><b>${esc(s.label)}</b>${s.rating ? `<div class="score">${esc(s.rating)}</div>` : ""}<p>${esc(s.text)}</p></div>`).join("")}</aside></div>${sub(rd.fourTitle, "The season-definers, tied to the thesis")}<div class="marquee4">${rd.four.map((f: any) => `<div class="mq"><small>${esc(f.when)}</small><b>${esc(f.opp)}</b><em>${esc(f.title)}</em><p>${esc(f.text)}</p></div>`).join("")}</div><div class="seasonline"><span><b>${esc(rd.record)}</b> &nbsp;· The season call</span><span>${esc(rd.seasonCall)}</span></div></div>${folio("JP Preseason Annual · 2026", pageNo())}</section>
<section class="page" id="p11">${head("The Ledger")}<div class="pin"><div class="spread"><h3>The August Ledger</h3><span class="tag">Every claim recorded · OPEN → HIT / MISS all season · ★ = Season-Definer</span></div><div class="ledger">${rd.ledgerRows.map((r: any) => `<div class="lr${/★/.test(r.opp) ? " dz" : ""}"><span class="d">${esc(r.date)}</span><span class="opp">${esc(r.opp)}</span><span class="tv">${esc(r.tv)}</span><span class="res${r.pick === "W" ? " w" : r.pick === "L" ? " l" : ""}">${esc(r.pick)}</span></div>`).join("")}<div class="lfoot"><span>${esc(rd.ledgerLine)}</span><span>TV/times = TBA</span></div></div>${sub(rd.trueTitle, rd.trueTag)}<div class="five">${rd.fiveTrue.map((t: any) => `<div class="ft"><div><h4>${esc(t.title)}</h4><p>${esc(t.text)}</p></div></div>`).join("")}</div>${sub("The margins", rd.marginsTag)}<div class="mrg">${rd.margins.map((m: any) => `<div class="mg"><small>${esc(m.label)}</small><b>${esc(m.big)}</b><h4>${esc(m.title)}</h4><p>${esc(m.text)}</p><div class="w">⏱ ${esc(m.watch)}</div></div>`).join("")}</div></div>${folio("JP Preseason Annual · 2026", pageNo())}</section>
<section class="page dark darkpg" id="p13">${head("The Flag Plant")}<div class="pin"><div class="spread"><h3>${esc(rd.flagTitle)}</h3><span class="tag">${esc(rd.flagTag)}</span></div><div class="seasons"><div class="sea c"><div class="k">The Ceiling</div><div class="rec">${esc(rd.ceiling)}</div><div class="sub">Everything holds</div></div><div class="sea p"><div class="k">The Pate Case — Flag Plant</div><div class="rec">${esc(rd.record)}</div><div class="sub">${esc(rd.seasonCall)}</div></div><div class="sea f"><div class="k">The Floor</div><div class="rec">${esc(rd.floor)}</div><div class="sub">What goes wrong</div></div></div>${rd.flag.map((p: string) => `<p style="max-width:70ch;margin:14px auto;font-size:16px;line-height:1.6;color:#e8e4d8">${md(p)}</p>`).join("")}<div class="flag"><div class="k">The Flag Plant · Ledger entry</div><div class="rec">${esc(rd.record)}</div><div class="status"><span class="open">⏳ Status: OPEN</span><span class="gd">Grading date: January 2027</span></div></div><div class="src"><b>Sources:</b> 2025 results and statistics — CFBD; 2026 schedule and polls — the site's fact sheet; reporting — ${esc([...new Set(readdirSync(`${D}/sources`).map((f) => f.split("-")[0]))].join(", "))} (Aug. 2026); Josh's on-record positions — the JP Poll and the published bracket. <div class="status"><span class="ok">Verified public data</span><span class="pp">Pate State proprietary (JP Poll, Model, grades)</span><span class="dm">Review draft — not published</span></div></div></div>${folio("patestate.com/annual", pageNo())}</section>`; }
let flags = "";
for (const id of ["opener", "autopsy", "offense", "defense", "marquee", "depth", "road"]) { const p = `${D}/out/${id}.json`; if (!existsSync(p)) continue; const f = JSON.parse(readFileSync(p, "utf8")).fact; const bad = (f?.claims ?? []).filter((c: any) => c.status === "unsupported" || c.status === "contradicted"); if (bad.length) flags += `<div class="fact-flag"><b>${id}</b> — ${bad.map((b: any) => `${b.status}: ${esc(b.claim)}`).join(" · ")}</div>`; }
html += `<div class="page" style="padding:26px 46px"><h3 style="font:800 22px/1 var(--cond);margin:0 0 8px">Fact-check appendix (review only)</h3><p style="font:500 13px/1.5 var(--body);color:var(--mut)">Every section was checked against the fact pack and the sources. Claims below were not supported or were contradicted by them; in a published annual each would be verified or cut.</p>${flags || "<p>No flags.</p>"}</div><footer><div class="in"><div class="flogo">The Pate <em>State</em></div><div class="fbase"><span>© The Pate State</span></div></div></footer>`;
writeFileSync(`docs/content/annual-${T.slug}-2026-sol.html`, html);
mkdirSync("public/annual", { recursive: true });
writeFileSync(`public/annual/${T.slug}.html`, `<!DOCTYPE html>\n<html lang="en">\n<head>\n<meta charset="UTF-8">\n<meta name="viewport" content="width=device-width, initial-scale=1">\n${html.match(/<title>[^<]*<\/title>/)![0]}\n${(html.match(/<link[^>]*>/g) ?? []).join("\n")}\n${html.match(/<style>[\s\S]*?<\/style>/)![0]}\n</head>\n<body>\n${html.replace(/<title>[^<]*<\/title>|<link[^>]*>|<style>[\s\S]*?<\/style>|<div class="fact-flag">[\s\S]*?<\/div>/g, "")}\n</body>\n</html>`);
console.log(`rendered docs/content/annual-${T.slug}-2026-sol.html and public/annual/${T.slug}.html · sections ${[op, au, of, df, mq, dp, rd].filter(Boolean).length}/7`);
